/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.Clock;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Pradeep
 */
public class sortingNew extends javax.swing.JFrame {

    /**
     * Creates new form sortingNew
     */
    public sortingNew() {
        initComponents();
        setVisible(true);
        setSize(2000,1200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        birthdate_sort4 = new javax.swing.JButton();
        amt_sort = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        visits_sort = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/sorting1.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        birthdate_sort4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        birthdate_sort4.setText("BirthDate");
        birthdate_sort4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdate_sort4ActionPerformed(evt);
            }
        });

        amt_sort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        amt_sort.setText("Amount");
        amt_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amt_sortActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Send offers  according to criteria");

        visits_sort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        visits_sort.setText("Vistis");
        visits_sort.setActionCommand("Visits");
        visits_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visits_sortActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("<<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_project/sorting.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amt_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visits_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdate_sort4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(birthdate_sort4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(amt_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                .addComponent(visits_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 140)); // NOI18N
        jLabel4.setText("Sorting");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amt_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amt_sortActionPerformed
        // TODO add your handling code here:
       String test = JOptionPane.showInputDialog(null,"Enter amount to whom we want ro send reedme points");
        String sendto = "";
     String msg = "Hello !        You have 10 rewards points on your last bill amount of above 500.          Don't forget to reedem this reward points next time you visit....Valid for seven days Regards 'KIS'  " ;
     String sub = "REEDEM POINTS";
JOptionPane.showMessageDialog(null, "Email sent to customers");
        try{
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_final","root","15091997");
            Statement st=conn.createStatement();
            Date d=new Date();

            //String str1=d.getDate()+"-"+(d.getMonth()+1);
            int i = Integer.parseInt(test);
            //System.out.println(str1);
            //String string="select cust_name,cust_mail from customer where dob= ? ";
            PreparedStatement pst2=conn.prepareStatement("select nameCust,email from billing where amount > ?");
            pst2.setInt(1,i);
            ResultSet rs=pst2.executeQuery();
            while(rs.next())
            {
                System.out.println(rs.getString(1)+" "+rs.getString(2));
                System.out.println(rs.getString(2));
                sendto = rs.getString(2);
                SendMailSSL.main(sendto,sub,msg);
                
            
            }
            pst2.executeQuery();
            
            pst2.close();
            // display
            
        }catch(Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_amt_sortActionPerformed
    @SuppressWarnings("unchecked")
    private void birthdate_sort4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdate_sort4ActionPerformed
     String test1 = JOptionPane.showInputDialog("Please enter Messege Here");
     
     String sendto = "";
     String msg = test1;
     String sub = "Happy Birthday";
JOptionPane.showMessageDialog(null, "Email sent to customers");
        try{
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_final","root","15091997");
            Statement st=conn.createStatement();
            Date d=new Date();

            String str1=d.getDate()+"-"+(d.getMonth()+1);
            System.out.println(str1);
            //String string="select cust_name,cust_mail from customer where dob= ? ";
            PreparedStatement pst2=conn.prepareStatement("select cust_name,email from customer where dob= ?");
            pst2.setString(1,str1);
            ResultSet rs=pst2.executeQuery();
            while(rs.next())
            {
                System.out.println(rs.getString(1)+" "+rs.getString(2));
                System.out.println(rs.getString(2));
                    sendto = rs.getString(2);
                    SendMailSSL.main(sendto,sub, msg);
                
            
            }
            pst2.executeQuery();
            
            pst2.close();
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_birthdate_sort4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mini_one_manager back = new mini_one_manager();
        back.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void visits_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visits_sortActionPerformed
        // TODO add your handling code here:
        String test1 = JOptionPane.showInputDialog("Please enter the visit date for checking ");
        
        
        String sendto = "";
     String msg = "Visit this weekend and get 20% discount on bill amount ";
     String sub = "Missing you";
     JOptionPane.showMessageDialog(null, "Email sent to customers");

        try{
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_final","root","15091997");
            Statement st=conn.createStatement();
            

            //String str1="2018-04-16";
           // System.out.println(str1);
            //String string="select cust_name,cust_mail from customer where dob= ? ";
            PreparedStatement pst2=conn.prepareStatement("select cust_name,email from customer where dov <  ?");
            pst2.setString(1,test1);
            ResultSet rs=pst2.executeQuery();
            while(rs.next())
            {
                System.out.println(rs.getString(1)+" "+rs.getString(2));
                System.out.println(rs.getString(2));
                sendto = rs.getString(2);
                SendMailSSL.main(sendto,sub, msg);
                
            
            }
            pst2.executeQuery();
            
            pst2.close();
            // display
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_visits_sortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sortingNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sortingNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sortingNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sortingNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sortingNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amt_sort;
    private javax.swing.JButton birthdate_sort4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton visits_sort;
    // End of variables declaration//GEN-END:variables
}
